In [83]:
!pip install pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2026.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [84]:

import numpy as np
import pandas as pd

In [85]:
a = [1,2,3,4,5,6]

In [86]:
s = pd.Series(a)

In [87]:
s

0    1
1    2
2    3
3    4
4    5
5    6
dtype: int64

In [88]:
import numpy as np
import pandas as pd

In [89]:
a = [1,2,3,4,5]

In [90]:
s = pd.Series(a)

In [91]:
s

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [92]:
b = {"alice": 89, "loki": 86,"thor": 90}

In [93]:
d = pd.Series(b)

In [94]:
d

alice    89
loki     86
thor     90
dtype: int64

In [95]:
import numpy as np
import pandas as pd

In [96]:
df = pd.read_csv('employees_100.csv')

In [97]:
df

,employee_id,name,department,city,age,salary,experience,performance_score,projects_completed,joining_date
0,184,Swati Kapoor,Data Science,Kolkata,38.0,70719,5,5,6,2021-07-02
1,154,Kavya Malhotra,engineering,Mumbai,NaN,77058,1,8,8,2024-02-05
2,171,Manish Desai,Data Science,Hyderabad,23.0,69911,0,6,18,2019-04-24
3,146,Neha Das,Engineering,Pune,28.0,69993,3,8,1,2022-12-13
4,145,Isha Nair,Data Science,NaN,32.0,88216,8,8,14,2019-11-25
...,...,...,...,...,...,...,...,...,...,...
95,161,Nikhil Nair,MARKETING,Chennai,22.0,55740,0,5,22,2020-04-22
96,172,Neha Desai,HR,Chennai,22.0,52250,0,5,7,2020-11-14
97,115,Neha Reddy,Marketing,Chennai,43.0,NaN,12,4,10,2019-06-06
98,193,Priya Nayak,HR,NaN,23.0,56821,3,9,16,2019-08-07
99,152,Kavya Joshi,Marketing,Delhi,44.0,69499,10,7,4,2022-03-25

In [98]:
df[df['department'].isin(['Engineering','Data science'])]

,employee_id,name,department,city,age,salary,experience,performance_score,projects_completed,joining_date
3,146,Neha Das,Engineering,Pune,28.0,69993,3,8,1,2022-12-13
8,111,Kavya Singh,Engineering,Delhi,23.0,NaN,1,5,10,2021-09-14
15,105,Vivek Pillai,Engineering,Pune,39.0,NaN,9,4,5,2024-06-05
19,132,Swati Malhotra,Engineering,Chennai,33.0,77222,5,7,15,2018-10-09
25,116,Rohan Verma,Engineering,Chennai,23.0,62693,0,4,8,2018-08-17
31,148,Kavya Nair,Engineering,Chennai,NaN,"76,320",3,7,11,2024-03-07
34,194,Pooja Menon,Engineering,Chennai,NaN,76281,7,4,9,2022-07-28
42,108,Ananya Rao,Engineering,Pune,38.0,78545,6,5,10,2022-02-16
60,157,Ananya Rao,Engineering,Mumbai,25.0,NaN,2,5,8,2022-04-07
63,144,Arjun Nayak,Engineering,Kolkata,38.0,75226,7,6,17,2019-12-27
65,168,Sanjay Kulkarni,Engineering,Delhi,34.0,80358,7,5,14,2020-04-01
66,147,Tanvi Verma,Engineering,Bangalore,35.0,77217,8,3,0,2022-04-22
84,102,Rahul Menon,Engineering,Hyderabad,38.0,84870,11,6,15,2021-06-07
92,187,Aditya Bose,Engineering,Bangalore,36.0,81112,7,4,9,2022-03-26

In [99]:
df[df['experience'].between(2,5)]

,employee_id,name,department,city,age,salary,experience,performance_score,projects_completed,joining_date
0,184,Swati Kapoor,Data Science,Kolkata,38.0,70719,5,5,6,2021-07-02
3,146,Neha Das,Engineering,Pune,28.0,69993,3,8,1,2022-12-13
6,123,Sneha Iyer,HR,Hyderabad,33.0,59895,4,4,18,2024-02-21
9,101,Ananya Malhotra,engineering,NaN,24.0,68591,2,8,0,2023-10-21
13,134,Vivek Kulkarni,Finance,Kolkata,24.0,59422,3,6,12,2021-11-24
14,191,Neha Malhotra,Marketing,Mumbai,29.0,64944,2,10,18,2023-10-05
16,177,Vivek Malhotra,Finance,Bangalore,NaN,NaN,3,4,12,2021-09-12
17,178,Vikram Kapoor,Sales,Chennai,29.0,57858,3,7,1,2020-06-26
19,132,Swati Malhotra,Engineering,Chennai,33.0,77222,5,7,15,2018-10-09
22,127,Suresh Verma,Data Science,Bangalore,27.0,"72,862",2,6,10,2023-02-21
24,170,Rahul Nair,Data Science,Kolkata,30.0,76425,5,2,4,2021-06-25
26,141,Manish Kulkarni,HR,Chennai,27.0,"45,835",3,8,13,2022-07-21
27,162,Suresh Chatterjee,HR,Hyderabad,32.0,59273,5,6,11,2020-09-05
28,110,Arjun Verma,Marketing,Pune,29.0,62227,4,7,8,2022-04-05
29,173,Riya Shah,Marketing,Bangalore,27.0,"62,165",5,5,6,2021-10-07
30,112,Aditya Reddy,Finance,NaN,31.0,58811,2,3,3,2020-05-26
31,148,Kavya Nair,Engineering,Chennai,NaN,"76,320",3,7,11,2024-03-07
35,106,Vivek Singh,HR,Delhi,27.0,56886,3,6,11,2020-08-04
36,167,Meera Malhotra,HR,Hyderabad,31.0,48822,4,5,4,2022-06-24
37,166,Meera Nayak,HR,Hyderabad,33.0,56940,4,7,13,2023-04-14
38,136,Sanjay Mehta,Sales,Hyderabad,30.0,52573,5,7,8,2021-02-12
41,135,Meera Desai,Marketing,Kolkata,28.0,59186,4,6,8,2023-07-10
53,139,Rahul Malhotra,Marketing,Hyderabad,23.0,60203,2,6,15,2022-09-17
54,109,Rohan Kulkarni,Data Science,Delhi,28.0,76267,5,6,3,2023-01-24
60,157,Ananya Rao,Engineering,Mumbai,25.0,NaN,2,5,8,2022-04-07
64,151,Sneha Verma,Finance,Delhi,NaN,66422,5,6,5,2023-09-02
67,169,Swati Chatterjee,HR,Pune,33.0,49801,3,6,11,2021-08-20
68,162,Suresh Chatterjee,HR,Hyderabad,32.0,59273,5,7,11,2020-09-05
69,134,Vivek Kulkarni,Finance,Kolkata,24.0,59422,3,6,13,2021-11-24
70,180,Ashok Kulkarni,Finance,Kolkata,31.0,58777,3,5,9,2024-07-10
72,159,Rohan Menon,HR,Pune,26.0,56141,3,4,13,2023-01-03
77,133,Riya Verma,HR,Kolkata,26.0,59693,3,6,20,2024-05-08
79,160,Shreya Singh,Finance,Pune,38.0,62020,5,5,0,2019-05-11
86,122,Ashok Shah,HR,Hyderabad,31.0,55756,5,8,11,2024-05-11
91,175,Aman Nayak,NaN,NaN,27.0,69076,5,5,10,2019-09-15
93,183,Deepak Nayak,Marketing,Hyderabad,28.0,62393,2,5,13,2020-08-09
94,121,Ashok Shah,Data Science,Pune,31.0,75498,4,7,7,2024-12-05
98,193,Priya Nayak,HR,NaN,23.0,56821,3,9,16,2019-08-07

In [100]:
df[df["name"].str.contains("kapoor")]

Empty DataFrame
Columns: [employee_id, name, department, city, age, salary, experience, performance_score, projects_completed, joining_date]
Index: []

In [101]:
df.isnull().sum()

employee_id            0
name                   0
department             8
city                  10
age                    6
salary                 8
experience             0
performance_score      0
projects_completed     0
joining_date           0
dtype: int64

In [102]:
df1 = df.dropna(subset = ['city','age'])

In [103]:
df1.isnull().sum()

employee_id           0
name                  0
department            7
city                  0
age                   0
salary                6
experience            0
performance_score     0
projects_completed    0
joining_date          0
dtype: int64

In [104]:
df['age'].fillna(df['age'].mean(),inplace = True)

/tmp/ipykernel_2916/240904280.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['age'].fillna(df['age'].mean(),inplace = True)

In [105]:
df.isnull().sum()

employee_id            0
name                   0
department             8
city                  10
age                    0
salary                 8
experience             0
performance_score      0
projects_completed     0
joining_date           0
dtype: int64

In [106]:
df['salary'] = df['salary'].str.replace(",", "", regex=False)
df['salary'] = pd.to_numeric(df['salary'], errors = 'coerce')
df['salary'] = df['salary'].fillna(df['salary'].median())

In [107]:
df['salary'].dtype

dtype('float64')

In [108]:
df.isnull().sum()

employee_id            0
name                   0
department             8
city                  10
age                    0
salary                 0
experience             0
performance_score      0
projects_completed     0
joining_date           0
dtype: int64

In [109]:
df['department'] = df['department'].fillna(df['department'].mode()[0])

In [110]:
df.isnull().sum()

employee_id            0
name                   0
department             0
city                  10
age                    0
salary                 0
experience             0
performance_score      0
projects_completed     0
joining_date           0
dtype: int64

In [111]:
df['city'] = df['city'].fillna(df['city'].mode()[0])

In [112]:
df.isnull().sum()

employee_id           0
name                  0
department            0
city                  0
age                   0
salary                0
experience            0
performance_score     0
projects_completed    0
joining_date          0
dtype: int64

In [113]:
df.duplicated().sum()

np.int64(0)

In [114]:
df.duplicated(subset = ['employee_id']).sum()

np.int64(4)

In [115]:
df.drop_duplicates(subset = ['employee_id'],keep = "first")

,employee_id,name,department,city,age,salary,experience,performance_score,projects_completed,joining_date
0,184,Swati Kapoor,Data Science,Kolkata,38.000000,70719.0,5,5,6,2021-07-02
1,154,Kavya Malhotra,engineering,Mumbai,30.861702,77058.0,1,8,8,2024-02-05
2,171,Manish Desai,Data Science,Hyderabad,23.000000,69911.0,0,6,18,2019-04-24
3,146,Neha Das,Engineering,Pune,28.000000,69993.0,3,8,1,2022-12-13
4,145,Isha Nair,Data Science,Hyderabad,32.000000,88216.0,8,8,14,2019-11-25
...,...,...,...,...,...,...,...,...,...,...
95,161,Nikhil Nair,MARKETING,Chennai,22.000000,55740.0,0,5,22,2020-04-22
96,172,Neha Desai,HR,Chennai,22.000000,52250.0,0,5,7,2020-11-14
97,115,Neha Reddy,Marketing,Chennai,43.000000,62969.5,12,4,10,2019-06-06
98,193,Priya Nayak,HR,Hyderabad,23.000000,56821.0,3,9,16,2019-08-07
99,152,Kavya Joshi,Marketing,Delhi,44.000000,69499.0,10,7,4,2022-03-25

In [116]:
import numpy as np
import pandas as pd

In [117]:
pd.Series([1,2,3,4,5])

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [118]:
pd.DataFrame({
    "name":["loki","thor","jane"],
    "age":[27,29,25]
})

   name  age
0  loki   27
1  thor   29
2  jane   25

In [119]:
pd.DataFrame({"name": "loki","salary":40000},
             {"name": "thor","salary": 50000})

        name  salary
name    loki   40000
salary  loki   40000

In [120]:
df = pd.read_csv("employees_100.csv")

In [121]:
df

,employee_id,name,department,city,age,salary,experience,performance_score,projects_completed,joining_date
0,184,Swati Kapoor,Data Science,Kolkata,38.0,70719,5,5,6,2021-07-02
1,154,Kavya Malhotra,engineering,Mumbai,NaN,77058,1,8,8,2024-02-05
2,171,Manish Desai,Data Science,Hyderabad,23.0,69911,0,6,18,2019-04-24
3,146,Neha Das,Engineering,Pune,28.0,69993,3,8,1,2022-12-13
4,145,Isha Nair,Data Science,NaN,32.0,88216,8,8,14,2019-11-25
...,...,...,...,...,...,...,...,...,...,...
95,161,Nikhil Nair,MARKETING,Chennai,22.0,55740,0,5,22,2020-04-22
96,172,Neha Desai,HR,Chennai,22.0,52250,0,5,7,2020-11-14
97,115,Neha Reddy,Marketing,Chennai,43.0,NaN,12,4,10,2019-06-06
98,193,Priya Nayak,HR,NaN,23.0,56821,3,9,16,2019-08-07
99,152,Kavya Joshi,Marketing,Delhi,44.0,69499,10,7,4,2022-03-25

In [122]:
df.head()

,employee_id,name,department,city,age,salary,experience,performance_score,projects_completed,joining_date
0,184,Swati Kapoor,Data Science,Kolkata,38.0,70719,5,5,6,2021-07-02
1,154,Kavya Malhotra,engineering,Mumbai,NaN,77058,1,8,8,2024-02-05
2,171,Manish Desai,Data Science,Hyderabad,23.0,69911,0,6,18,2019-04-24
3,146,Neha Das,Engineering,Pune,28.0,69993,3,8,1,2022-12-13
4,145,Isha Nair,Data Science,NaN,32.0,88216,8,8,14,2019-11-25

In [123]:
df.tail()

,employee_id,name,department,city,age,salary,experience,performance_score,projects_completed,joining_date
95,161,Nikhil Nair,MARKETING,Chennai,22.0,55740,0,5,22,2020-04-22
96,172,Neha Desai,HR,Chennai,22.0,52250,0,5,7,2020-11-14
97,115,Neha Reddy,Marketing,Chennai,43.0,NaN,12,4,10,2019-06-06
98,193,Priya Nayak,HR,NaN,23.0,56821,3,9,16,2019-08-07
99,152,Kavya Joshi,Marketing,Delhi,44.0,69499,10,7,4,2022-03-25

In [124]:
df.sample()

,employee_id,name,department,city,age,salary,experience,performance_score,projects_completed,joining_date
36,167,Meera Malhotra,HR,Hyderabad,31.0,48822,4,5,4,2022-06-24

In [125]:
df.shape

(100, 10)

In [126]:
df.dtypes

employee_id             int64
name                   object
department             object
city                   object
age                   float64
salary                 object
experience              int64
performance_score       int64
projects_completed      int64
joining_date           object
dtype: object

In [127]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   employee_id         100 non-null    int64
 1   name                100 non-null    object
 2   department          92 non-null     object
 3   city                90 non-null     object
 4   age                 94 non-null     float64
 5   salary              92 non-null     object
 6   experience          100 non-null    int64
 7   performance_score   100 non-null    int64
 8   projects_completed  100 non-null    int64
 9   joining_date        100 non-null    object
dtypes: float64(1), int64(4), object(5)
memory usage: 7.9+ KB

In [128]:
df.describe()

,employee_id,age,experience,performance_score,projects_completed
count,100.000000,94.000000,100.000000,100.0000,100.000000
mean,148.740000,30.861702,4.830000,5.7500,9.970000
std,27.420637,6.483397,3.755279,1.7019,5.332301
min,101.000000,22.000000,0.000000,2.0000,0.000000
25%,125.750000,25.250000,2.000000,5.0000,6.000000
50%,149.500000,31.000000,4.500000,6.0000,9.500000
75%,171.250000,35.750000,8.000000,7.0000,13.250000
max,196.000000,45.000000,17.000000,10.0000,24.000000

In [129]:
df['salary']

0     70719
1     77058
2     69911
3     69993
4     88216
      ...
95    55740
96    52250
97      NaN
98    56821
99    69499
Name: salary, Length: 100, dtype: object

In [130]:
df[['name','age','department']]

              name   age    department
0     Swati Kapoor  38.0  Data Science
1   Kavya Malhotra   NaN   engineering
2     Manish Desai  23.0  Data Science
3         Neha Das  28.0   Engineering
4        Isha Nair  32.0  Data Science
..             ...   ...           ...
95     Nikhil Nair  22.0     MARKETING
96      Neha Desai  22.0            HR
97      Neha Reddy  43.0     Marketing
98     Priya Nayak  23.0            HR
99     Kavya Joshi  44.0     Marketing

[100 rows x 3 columns]

In [131]:
df.loc[9]

employee_id                       101
name                  Ananya Malhotra
department                engineering
city                              NaN
age                              24.0
salary                          68591
experience                          2
performance_score                   8
projects_completed                  0
joining_date               2023-10-21
Name: 9, dtype: object

In [132]:
df.iloc[0]

employee_id                    184
name                  Swati Kapoor
department            Data Science
city                       Kolkata
age                           38.0
salary                       70719
experience                       5
performance_score                5
projects_completed               6
joining_date            2021-07-02
Name: 0, dtype: object

In [133]:
df[(df['department'] == 'HR') & (df['age'] > 25)]

,employee_id,name,department,city,age,salary,experience,performance_score,projects_completed,joining_date
6,123,Sneha Iyer,HR,Hyderabad,33.0,59895,4,4,18,2024-02-21
26,141,Manish Kulkarni,HR,Chennai,27.0,"45,835",3,8,13,2022-07-21
35,106,Vivek Singh,HR,Delhi,27.0,56886,3,6,11,2020-08-04
36,167,Meera Malhotra,HR,Hyderabad,31.0,48822,4,5,4,2022-06-24
37,166,Meera Nayak,HR,Hyderabad,33.0,56940,4,7,13,2023-04-14
56,107,Karan Mehta,HR,Delhi,34.0,55119,8,3,8,2021-07-02
67,169,Swati Chatterjee,HR,Pune,33.0,49801,3,6,11,2021-08-20
72,159,Rohan Menon,HR,Pune,26.0,56141,3,4,13,2023-01-03
77,133,Riya Verma,HR,Kolkata,26.0,59693,3,6,20,2024-05-08
86,122,Ashok Shah,HR,Hyderabad,31.0,55756,5,8,11,2024-05-11
89,188,Sanjay Verma,HR,Bangalore,33.0,59591,8,4,4,2019-03-05
90,192,Divya Verma,HR,Delhi,40.0,66363,12,7,13,2022-09-10

In [134]:
import pandas as pd
import numpy as np
df = pd.read_csv("employees_100.csv")
df = pd.to_numeric(df['salary'], errors = 'coerce')

In [135]:
df.head()

0    70719.0
1    77058.0
2    69911.0
3    69993.0
4    88216.0
Name: salary, dtype: float64

In [136]:
df.dtypes

dtype('float64')

In [137]:
df.info()

<class 'pandas.core.series.Series'>
RangeIndex: 100 entries, 0 to 99
Series name: salary
Non-Null Count  Dtype
--------------  -----
83 non-null     float64
dtypes: float64(1)
memory usage: 932.0 bytes

In [138]:
import numpy as np
import pandas as pd

In [139]:
df  = pd.read_csv("employees_100.csv")

In [140]:
df.sort_values(by=['department'])

,employee_id,name,department,city,age,salary,experience,performance_score,projects_completed,joining_date
16,177,Vivek Malhotra,Finance,Bangalore,NaN,NaN,3,4,12,2021-09-12
27,162,Suresh Chatterjee,HR,Hyderabad,32.0,59273,5,6,11,2020-09-05
68,162,Suresh Chatterjee,HR,Hyderabad,32.0,59273,5,7,11,2020-09-05
11,131,Priya Malhotra,Marketing,Hyderabad,25.0,55295,1,7,12,2022-02-13
0,184,Swati Kapoor,Data Science,Kolkata,38.0,70719,5,5,6,2021-07-02
...,...,...,...,...,...,...,...,...,...,...
74,158,Tanvi Malhotra,NaN,Mumbai,32.0,"88,366",11,5,19,2021-02-26
75,158,Tanvi Malhotra,NaN,Mumbai,32.0,"88,366",11,6,17,2021-02-26
80,164,Sneha Gupta,NaN,Delhi,42.0,63209,11,4,7,2021-08-07
81,185,Vikram Desai,NaN,Pune,39.0,68197,9,4,9,2024-09-13
91,175,Aman Nayak,NaN,NaN,27.0,69076,5,5,10,2019-09-15

In [141]:
pd.Series(['loki','thor'])

0    loki
1    thor
dtype: object

In [142]:
pd.DataFrame({
    'name':['loki','thor'],
    'age':[27,29]
})

   name  age
0  loki   27
1  thor   29

In [143]:
df.head()

,employee_id,name,department,city,age,salary,experience,performance_score,projects_completed,joining_date
0,184,Swati Kapoor,Data Science,Kolkata,38.0,70719,5,5,6,2021-07-02
1,154,Kavya Malhotra,engineering,Mumbai,NaN,77058,1,8,8,2024-02-05
2,171,Manish Desai,Data Science,Hyderabad,23.0,69911,0,6,18,2019-04-24
3,146,Neha Das,Engineering,Pune,28.0,69993,3,8,1,2022-12-13
4,145,Isha Nair,Data Science,NaN,32.0,88216,8,8,14,2019-11-25

In [144]:
df.tail()

,employee_id,name,department,city,age,salary,experience,performance_score,projects_completed,joining_date
95,161,Nikhil Nair,MARKETING,Chennai,22.0,55740,0,5,22,2020-04-22
96,172,Neha Desai,HR,Chennai,22.0,52250,0,5,7,2020-11-14
97,115,Neha Reddy,Marketing,Chennai,43.0,NaN,12,4,10,2019-06-06
98,193,Priya Nayak,HR,NaN,23.0,56821,3,9,16,2019-08-07
99,152,Kavya Joshi,Marketing,Delhi,44.0,69499,10,7,4,2022-03-25

In [145]:
df.sample()

,employee_id,name,department,city,age,salary,experience,performance_score,projects_completed,joining_date
47,126,Neha Desai,HR,Delhi,22.0,"53,011",0,5,8,2023-07-19

In [146]:
df.shape

(100, 10)

In [147]:
df.dtypes

employee_id             int64
name                   object
department             object
city                   object
age                   float64
salary                 object
experience              int64
performance_score       int64
projects_completed      int64
joining_date           object
dtype: object

In [148]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   employee_id         100 non-null    int64
 1   name                100 non-null    object
 2   department          92 non-null     object
 3   city                90 non-null     object
 4   age                 94 non-null     float64
 5   salary              92 non-null     object
 6   experience          100 non-null    int64
 7   performance_score   100 non-null    int64
 8   projects_completed  100 non-null    int64
 9   joining_date        100 non-null    object
dtypes: float64(1), int64(4), object(5)
memory usage: 7.9+ KB

In [149]:
df.describe()

,employee_id,age,experience,performance_score,projects_completed
count,100.000000,94.000000,100.000000,100.0000,100.000000
mean,148.740000,30.861702,4.830000,5.7500,9.970000
std,27.420637,6.483397,3.755279,1.7019,5.332301
min,101.000000,22.000000,0.000000,2.0000,0.000000
25%,125.750000,25.250000,2.000000,5.0000,6.000000
50%,149.500000,31.000000,4.500000,6.0000,9.500000
75%,171.250000,35.750000,8.000000,7.0000,13.250000
max,196.000000,45.000000,17.000000,10.0000,24.000000

In [150]:
df[['salary','department','age']]

   salary    department   age
0   70719  Data Science  38.0
1   77058   engineering   NaN
2   69911  Data Science  23.0
3   69993   Engineering  28.0
4   88216  Data Science  32.0
..    ...           ...   ...
95  55740     MARKETING  22.0
96  52250            HR  22.0
97    NaN     Marketing  43.0
98  56821            HR  23.0
99  69499     Marketing  44.0

[100 rows x 3 columns]

In [151]:
df = df.set_index('employee_id')

In [152]:
df.head()

,name,department,city,age,salary,experience,performance_score,projects_completed,joining_date
employee_id,,,,,,,,,
184,Swati Kapoor,Data Science,Kolkata,38.0,70719,5,5,6,2021-07-02
154,Kavya Malhotra,engineering,Mumbai,NaN,77058,1,8,8,2024-02-05
171,Manish Desai,Data Science,Hyderabad,23.0,69911,0,6,18,2019-04-24
146,Neha Das,Engineering,Pune,28.0,69993,3,8,1,2022-12-13
145,Isha Nair,Data Science,NaN,32.0,88216,8,8,14,2019-11-25

In [153]:
df.loc[184:145]

,name,department,city,age,salary,experience,performance_score,projects_completed,joining_date
employee_id,,,,,,,,,
184,Swati Kapoor,Data Science,Kolkata,38.0,70719,5,5,6,2021-07-02
154,Kavya Malhotra,engineering,Mumbai,NaN,77058,1,8,8,2024-02-05
171,Manish Desai,Data Science,Hyderabad,23.0,69911,0,6,18,2019-04-24
146,Neha Das,Engineering,Pune,28.0,69993,3,8,1,2022-12-13
145,Isha Nair,Data Science,NaN,32.0,88216,8,8,14,2019-11-25

In [154]:
df.iloc[0:10]

,name,department,city,age,salary,experience,performance_score,projects_completed,joining_date
employee_id,,,,,,,,,
184,Swati Kapoor,Data Science,Kolkata,38.0,70719,5,5,6,2021-07-02
154,Kavya Malhotra,engineering,Mumbai,NaN,77058,1,8,8,2024-02-05
171,Manish Desai,Data Science,Hyderabad,23.0,69911,0,6,18,2019-04-24
146,Neha Das,Engineering,Pune,28.0,69993,3,8,1,2022-12-13
145,Isha Nair,Data Science,NaN,32.0,88216,8,8,14,2019-11-25
140,Rahul Gupta,Sales,Hyderabad,23.0,52404,0,9,13,2018-12-27
123,Sneha Iyer,HR,Hyderabad,33.0,59895,4,4,18,2024-02-21
181,Karan Rao,Marketing,NaN,22.0,50733,1,6,6,2020-04-05
111,Kavya Singh,Engineering,Delhi,23.0,NaN,1,5,10,2021-09-14
101,Ananya Malhotra,engineering,NaN,24.0,68591,2,8,0,2023-10-21

In [155]:
df.loc[184:145][['name','age','salary']]

                       name   age salary
employee_id
184            Swati Kapoor  38.0  70719
154          Kavya Malhotra   NaN  77058
171            Manish Desai  23.0  69911
146                Neha Das  28.0  69993
145               Isha Nair  32.0  88216

In [156]:
df.iloc[1:6][['name','age','salary']]

                       name   age salary
employee_id
154          Kavya Malhotra   NaN  77058
171            Manish Desai  23.0  69911
146                Neha Das  28.0  69993
145               Isha Nair  32.0  88216
140             Rahul Gupta  23.0  52404

In [157]:
df[(df['experience']>3) & (df['age'] > 35)]

,name,department,city,age,salary,experience,performance_score,projects_completed,joining_date
employee_id,,,,,,,,,
184,Swati Kapoor,Data Science,Kolkata,38.0,70719,5,5,6,2021-07-02
105,Vivek Pillai,Engineering,Pune,39.0,NaN,9,4,5,2024-06-05
113,Ritu Nair,Finance,NaN,41.0,74778,10,7,5,2018-02-13
143,Neha Rao,Sales,Hyderabad,37.0,NaN,11,6,11,2023-05-15
186,Rohan Kapoor,NaN,Pune,36.0,65152,8,7,4,2020-02-15
108,Ananya Rao,Engineering,Pune,38.0,78545,6,5,10,2022-02-16
179,Arjun Das,Finance,NaN,43.0,NaN,10,7,11,2024-08-25
165,Isha Das,Marketing,Pune,40.0,57895,6,5,1,2023-08-16
137,Ritu Bose,Finance,Bangalore,38.0,71062,8,6,4,2023-12-19
164,Sneha Gupta,NaN,Delhi,42.0,63209,11,3,8,2021-08-07
155,Sanjay Das,NaN,Bangalore,45.0,74505,17,6,10,2022-06-22
144,Arjun Nayak,Engineering,Kolkata,38.0,75226,7,6,17,2019-12-27
149,Sanjay Desai,SALES,Hyderabad,37.0,"62,730",8,7,8,2019-01-23
176,Shreya Menon,Finance,NaN,41.0,80597,9,2,18,2024-11-09
160,Shreya Singh,Finance,Pune,38.0,62020,5,5,0,2019-05-11
164,Sneha Gupta,NaN,Delhi,42.0,63209,11,4,7,2021-08-07
185,Vikram Desai,NaN,Pune,39.0,68197,9,4,9,2024-09-13
102,Rahul Menon,Engineering,Hyderabad,38.0,84870,11,6,15,2021-06-07
103,Ananya Nayak,Sales,Delhi,38.0,68490,9,6,6,2021-11-19
124,Deepak Verma,Data Science,Hyderabad,41.0,86380,9,7,8,2024-06-05
192,Divya Verma,HR,Delhi,40.0,66363,12,7,13,2022-09-10
187,Aditya Bose,Engineering,Bangalore,36.0,81112,7,4,9,2022-03-26
115,Neha Reddy,Marketing,Chennai,43.0,NaN,12,4,10,2019-06-06
152,Kavya Joshi,Marketing,Delhi,44.0,69499,10,7,4,2022-03-25

In [158]:
df[(df['department'] == 'finance') | (df['department'] == 'HR')]

,name,department,city,age,salary,experience,performance_score,projects_completed,joining_date
employee_id,,,,,,,,,
123,Sneha Iyer,HR,Hyderabad,33.0,59895,4,4,18,2024-02-21
141,Manish Kulkarni,HR,Chennai,27.0,"45,835",3,8,13,2022-07-21
106,Vivek Singh,HR,Delhi,27.0,56886,3,6,11,2020-08-04
167,Meera Malhotra,HR,Hyderabad,31.0,48822,4,5,4,2022-06-24
166,Meera Nayak,HR,Hyderabad,33.0,56940,4,7,13,2023-04-14
150,Vivek Chatterjee,HR,Kolkata,22.0,51391,0,7,8,2019-11-20
126,Neha Desai,HR,Delhi,22.0,"53,011",0,5,8,2023-07-19
107,Karan Mehta,HR,Delhi,34.0,55119,8,3,8,2021-07-02
169,Swati Chatterjee,HR,Pune,33.0,49801,3,6,11,2021-08-20
142,Shreya Das,HR,Pune,22.0,56504,0,7,2,2021-06-19
159,Rohan Menon,HR,Pune,26.0,56141,3,4,13,2023-01-03
133,Riya Verma,HR,Kolkata,26.0,59693,3,6,20,2024-05-08
122,Ashok Shah,HR,Hyderabad,31.0,55756,5,8,11,2024-05-11
188,Sanjay Verma,HR,Bangalore,33.0,59591,8,4,4,2019-03-05
192,Divya Verma,HR,Delhi,40.0,66363,12,7,13,2022-09-10
172,Neha Desai,HR,Chennai,22.0,52250,0,5,7,2020-11-14
193,Priya Nayak,HR,NaN,23.0,56821,3,9,16,2019-08-07

In [159]:
df[~(df['name'] == 'Swati')]

,name,department,city,age,salary,experience,performance_score,projects_completed,joining_date
employee_id,,,,,,,,,
184,Swati Kapoor,Data Science,Kolkata,38.0,70719,5,5,6,2021-07-02
154,Kavya Malhotra,engineering,Mumbai,NaN,77058,1,8,8,2024-02-05
171,Manish Desai,Data Science,Hyderabad,23.0,69911,0,6,18,2019-04-24
146,Neha Das,Engineering,Pune,28.0,69993,3,8,1,2022-12-13
145,Isha Nair,Data Science,NaN,32.0,88216,8,8,14,2019-11-25
...,...,...,...,...,...,...,...,...,...
161,Nikhil Nair,MARKETING,Chennai,22.0,55740,0,5,22,2020-04-22
172,Neha Desai,HR,Chennai,22.0,52250,0,5,7,2020-11-14
115,Neha Reddy,Marketing,Chennai,43.0,NaN,12,4,10,2019-06-06
193,Priya Nayak,HR,NaN,23.0,56821,3,9,16,2019-08-07
152,Kavya Joshi,Marketing,Delhi,44.0,69499,10,7,4,2022-03-25

In [160]:
df[df['department'].isin(['finance','HR','data science'])]

,name,department,city,age,salary,experience,performance_score,projects_completed,joining_date
employee_id,,,,,,,,,
123,Sneha Iyer,HR,Hyderabad,33.0,59895,4,4,18,2024-02-21
141,Manish Kulkarni,HR,Chennai,27.0,"45,835",3,8,13,2022-07-21
106,Vivek Singh,HR,Delhi,27.0,56886,3,6,11,2020-08-04
167,Meera Malhotra,HR,Hyderabad,31.0,48822,4,5,4,2022-06-24
166,Meera Nayak,HR,Hyderabad,33.0,56940,4,7,13,2023-04-14
150,Vivek Chatterjee,HR,Kolkata,22.0,51391,0,7,8,2019-11-20
126,Neha Desai,HR,Delhi,22.0,"53,011",0,5,8,2023-07-19
107,Karan Mehta,HR,Delhi,34.0,55119,8,3,8,2021-07-02
169,Swati Chatterjee,HR,Pune,33.0,49801,3,6,11,2021-08-20
142,Shreya Das,HR,Pune,22.0,56504,0,7,2,2021-06-19
159,Rohan Menon,HR,Pune,26.0,56141,3,4,13,2023-01-03
133,Riya Verma,HR,Kolkata,26.0,59693,3,6,20,2024-05-08
122,Ashok Shah,HR,Hyderabad,31.0,55756,5,8,11,2024-05-11
188,Sanjay Verma,HR,Bangalore,33.0,59591,8,4,4,2019-03-05
192,Divya Verma,HR,Delhi,40.0,66363,12,7,13,2022-09-10
172,Neha Desai,HR,Chennai,22.0,52250,0,5,7,2020-11-14
193,Priya Nayak,HR,NaN,23.0,56821,3,9,16,2019-08-07

In [161]:
df[df['experience'].between(3,5)]

,name,department,city,age,salary,experience,performance_score,projects_completed,joining_date
employee_id,,,,,,,,,
184,Swati Kapoor,Data Science,Kolkata,38.0,70719,5,5,6,2021-07-02
146,Neha Das,Engineering,Pune,28.0,69993,3,8,1,2022-12-13
123,Sneha Iyer,HR,Hyderabad,33.0,59895,4,4,18,2024-02-21
134,Vivek Kulkarni,Finance,Kolkata,24.0,59422,3,6,12,2021-11-24
177,Vivek Malhotra,Finance,Bangalore,NaN,NaN,3,4,12,2021-09-12
178,Vikram Kapoor,Sales,Chennai,29.0,57858,3,7,1,2020-06-26
132,Swati Malhotra,Engineering,Chennai,33.0,77222,5,7,15,2018-10-09
170,Rahul Nair,Data Science,Kolkata,30.0,76425,5,2,4,2021-06-25
141,Manish Kulkarni,HR,Chennai,27.0,"45,835",3,8,13,2022-07-21
162,Suresh Chatterjee,HR,Hyderabad,32.0,59273,5,6,11,2020-09-05
110,Arjun Verma,Marketing,Pune,29.0,62227,4,7,8,2022-04-05
173,Riya Shah,Marketing,Bangalore,27.0,"62,165",5,5,6,2021-10-07
148,Kavya Nair,Engineering,Chennai,NaN,"76,320",3,7,11,2024-03-07
106,Vivek Singh,HR,Delhi,27.0,56886,3,6,11,2020-08-04
167,Meera Malhotra,HR,Hyderabad,31.0,48822,4,5,4,2022-06-24
166,Meera Nayak,HR,Hyderabad,33.0,56940,4,7,13,2023-04-14
136,Sanjay Mehta,Sales,Hyderabad,30.0,52573,5,7,8,2021-02-12
135,Meera Desai,Marketing,Kolkata,28.0,59186,4,6,8,2023-07-10
109,Rohan Kulkarni,Data Science,Delhi,28.0,76267,5,6,3,2023-01-24
151,Sneha Verma,Finance,Delhi,NaN,66422,5,6,5,2023-09-02
169,Swati Chatterjee,HR,Pune,33.0,49801,3,6,11,2021-08-20
162,Suresh Chatterjee,HR,Hyderabad,32.0,59273,5,7,11,2020-09-05
134,Vivek Kulkarni,Finance,Kolkata,24.0,59422,3,6,13,2021-11-24
180,Ashok Kulkarni,Finance,Kolkata,31.0,58777,3,5,9,2024-07-10
159,Rohan Menon,HR,Pune,26.0,56141,3,4,13,2023-01-03
133,Riya Verma,HR,Kolkata,26.0,59693,3,6,20,2024-05-08
160,Shreya Singh,Finance,Pune,38.0,62020,5,5,0,2019-05-11
122,Ashok Shah,HR,Hyderabad,31.0,55756,5,8,11,2024-05-11
175,Aman Nayak,NaN,NaN,27.0,69076,5,5,10,2019-09-15
121,Ashok Shah,Data Science,Pune,31.0,75498,4,7,7,2024-12-05
193,Priya Nayak,HR,NaN,23.0,56821,3,9,16,2019-08-07

In [162]:
df[df['name'].str.contains('Verma')]

,name,department,city,age,salary,experience,performance_score,projects_completed,joining_date
employee_id,,,,,,,,,
127,Suresh Verma,Data Science,Bangalore,27.0,"72,862",2,6,10,2023-02-21
116,Rohan Verma,Engineering,Chennai,23.0,62693,0,4,8,2018-08-17
110,Arjun Verma,Marketing,Pune,29.0,62227,4,7,8,2022-04-05
151,Sneha Verma,Finance,Delhi,NaN,66422,5,6,5,2023-09-02
147,Tanvi Verma,Engineering,Bangalore,35.0,77217,8,3,0,2022-04-22
133,Riya Verma,HR,Kolkata,26.0,59693,3,6,20,2024-05-08
124,Deepak Verma,Data Science,Hyderabad,41.0,86380,9,7,8,2024-06-05
188,Sanjay Verma,HR,Bangalore,33.0,59591,8,4,4,2019-03-05
192,Divya Verma,HR,Delhi,40.0,66363,12,7,13,2022-09-10

In [163]:
df.isna().sum()

name                   0
department             8
city                  10
age                    6
salary                 8
experience             0
performance_score      0
projects_completed     0
joining_date           0
dtype: int64

In [164]:
df2 = df.dropna(subset=['city','department','age','salary'])

In [165]:
df2.isna().sum()

name                  0
department            0
city                  0
age                   0
salary                0
experience            0
performance_score     0
projects_completed    0
joining_date          0
dtype: int64

In [166]:
df.duplicated().sum()

np.int64(0)

In [167]:
df.head()

,name,department,city,age,salary,experience,performance_score,projects_completed,joining_date
employee_id,,,,,,,,,
184,Swati Kapoor,Data Science,Kolkata,38.0,70719,5,5,6,2021-07-02
154,Kavya Malhotra,engineering,Mumbai,NaN,77058,1,8,8,2024-02-05
171,Manish Desai,Data Science,Hyderabad,23.0,69911,0,6,18,2019-04-24
146,Neha Das,Engineering,Pune,28.0,69993,3,8,1,2022-12-13
145,Isha Nair,Data Science,NaN,32.0,88216,8,8,14,2019-11-25

In [168]:
df['age'].fillna(df['age'].mean(),inplace = True)

/tmp/ipykernel_2916/240904280.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['age'].fillna(df['age'].mean(),inplace = True)

In [169]:
df.head()

,name,department,city,age,salary,experience,performance_score,projects_completed,joining_date
employee_id,,,,,,,,,
184,Swati Kapoor,Data Science,Kolkata,38.000000,70719,5,5,6,2021-07-02
154,Kavya Malhotra,engineering,Mumbai,30.861702,77058,1,8,8,2024-02-05
171,Manish Desai,Data Science,Hyderabad,23.000000,69911,0,6,18,2019-04-24
146,Neha Das,Engineering,Pune,28.000000,69993,3,8,1,2022-12-13
145,Isha Nair,Data Science,NaN,32.000000,88216,8,8,14,2019-11-25

In [170]:
df.isnull().sum()

name                   0
department             8
city                  10
age                    0
salary                 8
experience             0
performance_score      0
projects_completed     0
joining_date           0
dtype: int64

In [175]:
df['salary'] = df['salary'].str.replace(",","",regex = False)
df['salary'] = pd.to_numeric(df['salary'],errors = 'coerce')

In [176]:
df['salary'].fillna(df['salary'].median(),inplace = True)

/tmp/ipykernel_2916/2125179476.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['salary'].fillna(df['salary'].median(),inplace = True)

In [177]:
df.isnull().sum()

name                   0
department             8
city                  10
age                    0
salary                 0
experience             0
performance_score      0
projects_completed     0
joining_date           0
salary_rank            8
dtype: int64

In [178]:
df['salary'].dtypes

dtype('float64')

In [179]:
df['department'] = df['department'].fillna(df['department'].mode()[0])

In [180]:
df['city'] = df['city'].fillna(df['city'].mode()[0])

In [181]:
df.isnull().sum()

name                  0
department            0
city                  0
age                   0
salary                0
experience            0
performance_score     0
projects_completed    0
joining_date          0
salary_rank           8
dtype: int64

In [182]:
df.duplicated().sum()

np.int64(0)

In [183]:
df= df.reset_index()

In [184]:
df.duplicated(subset=['employee_id']).sum()

np.int64(4)

In [185]:
 df.drop_duplicates(subset=['employee_id'],keep='first',inplace=True)

In [186]:
df['joining_date'] = pd.to_datetime(df['joining_date'])

In [187]:
df.isnull().sum()

employee_id           0
name                  0
department            0
city                  0
age                   0
salary                0
experience            0
performance_score     0
projects_completed    0
joining_date          0
salary_rank           8
dtype: int64

In [188]:
df.dtypes

employee_id                    int64
name                          object
department                    object
city                          object
age                          float64
salary                       float64
experience                     int64
performance_score              int64
projects_completed             int64
joining_date          datetime64[ns]
salary_rank                  float64
dtype: object

In [189]:
df['annual_salary'] = df['salary'] * 12

In [190]:
df.head()

,employee_id,name,department,city,age,salary,experience,performance_score,projects_completed,joining_date,salary_rank,annual_salary
0,184,Swati Kapoor,Data Science,Kolkata,38.000000,70719.0,5,5,6,2021-07-02,27.0,848628.0
1,154,Kavya Malhotra,engineering,Mumbai,30.861702,77058.0,1,8,8,2024-02-05,14.0,924696.0
2,171,Manish Desai,Data Science,Hyderabad,23.000000,69911.0,0,6,18,2019-04-24,29.0,838932.0
3,146,Neha Das,Engineering,Pune,28.000000,69993.0,3,8,1,2022-12-13,28.0,839916.0
4,145,Isha Nair,Data Science,Hyderabad,32.000000,88216.0,8,8,14,2019-11-25,1.0,1058592.0

In [191]:
def categorise(num):
  if num > 5:
    return "experienced candidate"

  elif num <= 5:
    return "learner"

In [192]:
df['experience_status'] = df['experience'].apply(categorise)

In [193]:
df.head()

,employee_id,name,department,city,age,salary,experience,performance_score,projects_completed,joining_date,salary_rank,annual_salary,experience_status
0,184,Swati Kapoor,Data Science,Kolkata,38.000000,70719.0,5,5,6,2021-07-02,27.0,848628.0,learner
1,154,Kavya Malhotra,engineering,Mumbai,30.861702,77058.0,1,8,8,2024-02-05,14.0,924696.0,learner
2,171,Manish Desai,Data Science,Hyderabad,23.000000,69911.0,0,6,18,2019-04-24,29.0,838932.0,learner
3,146,Neha Das,Engineering,Pune,28.000000,69993.0,3,8,1,2022-12-13,28.0,839916.0,learner
4,145,Isha Nair,Data Science,Hyderabad,32.000000,88216.0,8,8,14,2019-11-25,1.0,1058592.0,experienced candidate

In [194]:
df.sort_values(by='salary')

,employee_id,name,department,city,age,salary,experience,performance_score,projects_completed,joining_date,salary_rank,annual_salary,experience_status
26,141,Manish Kulkarni,HR,Chennai,27.0,45835.0,3,8,13,2022-07-21,92.0,550020.0,learner
36,167,Meera Malhotra,HR,Hyderabad,31.0,48822.0,4,5,4,2022-06-24,91.0,585864.0,learner
33,129,Ashok Gupta,Marketing,Hyderabad,22.0,49693.0,0,4,7,2018-08-27,90.0,596316.0,learner
67,169,Swati Chatterjee,HR,Pune,33.0,49801.0,3,6,11,2021-08-20,89.0,597612.0,learner
7,181,Karan Rao,Marketing,Hyderabad,22.0,50733.0,1,6,6,2020-04-05,88.0,608796.0,learner
...,...,...,...,...,...,...,...,...,...,...,...,...,...
39,117,Pooja Malhotra,engineering,Kolkata,24.0,84255.0,1,8,19,2021-12-05,6.0,1011060.0,learner
84,102,Rahul Menon,Engineering,Hyderabad,38.0,84870.0,11,6,15,2021-06-07,5.0,1018440.0,experienced candidate
88,124,Deepak Verma,Data Science,Hyderabad,41.0,86380.0,9,7,8,2024-06-05,4.0,1036560.0,experienced candidate
4,145,Isha Nair,Data Science,Hyderabad,32.0,88216.0,8,8,14,2019-11-25,1.0,1058592.0,experienced candidate
74,158,Tanvi Malhotra,HR,Mumbai,32.0,88366.0,11,5,19,2021-02-26,2.5,1060392.0,experienced candidate

In [195]:
df['department'] = df['department'].str.strip().str.title()

In [196]:
df['department'].unique()

array(['Data Science', 'Engineering', 'Sales', 'Hr', 'Marketing',
       'Finance'], dtype=object)

In [197]:
df.sort_values(by=['department', 'salary'],ascending = [True, False])

,employee_id,name,department,city,age,salary,experience,performance_score,projects_completed,joining_date,salary_rank,annual_salary,experience_status
4,145,Isha Nair,Data Science,Hyderabad,32.0,88216.0,8,8,14,2019-11-25,1.0,1058592.0,experienced candidate
88,124,Deepak Verma,Data Science,Hyderabad,41.0,86380.0,9,7,8,2024-06-05,4.0,1036560.0,experienced candidate
59,190,Swati Bose,Data Science,Mumbai,22.0,78465.0,0,8,18,2022-11-22,11.0,941580.0,learner
24,170,Rahul Nair,Data Science,Kolkata,30.0,76425.0,5,2,4,2021-06-25,15.0,917100.0,learner
54,109,Rohan Kulkarni,Data Science,Delhi,28.0,76267.0,5,6,3,2023-01-24,17.0,915204.0,learner
...,...,...,...,...,...,...,...,...,...,...,...,...,...
48,163,Rahul Chatterjee,Sales,Kolkata,25.0,60015.0,0,8,9,2023-05-10,56.0,720180.0,learner
17,178,Vikram Kapoor,Sales,Chennai,29.0,57858.0,3,7,1,2020-06-26,69.0,694296.0,learner
44,128,Rohan Chatterjee,Sales,Mumbai,26.0,52862.0,1,3,7,2022-08-04,83.0,634344.0,learner
38,136,Sanjay Mehta,Sales,Hyderabad,30.0,52573.0,5,7,8,2021-02-12,84.0,630876.0,learner
5,140,Rahul Gupta,Sales,Hyderabad,23.0,52404.0,0,9,13,2018-12-27,85.0,628848.0,learner

In [198]:
df['salary_rank'] = df['salary'].rank(ascending=False)

In [199]:
df.sort_values(by='salary_rank')

,employee_id,name,department,city,age,salary,experience,performance_score,projects_completed,joining_date,salary_rank,annual_salary,experience_status
74,158,Tanvi Malhotra,Hr,Mumbai,32.0,88366.0,11,5,19,2021-02-26,1.0,1060392.0,experienced candidate
4,145,Isha Nair,Data Science,Hyderabad,32.0,88216.0,8,8,14,2019-11-25,2.0,1058592.0,experienced candidate
88,124,Deepak Verma,Data Science,Hyderabad,41.0,86380.0,9,7,8,2024-06-05,3.0,1036560.0,experienced candidate
84,102,Rahul Menon,Engineering,Hyderabad,38.0,84870.0,11,6,15,2021-06-07,4.0,1018440.0,experienced candidate
39,117,Pooja Malhotra,Engineering,Kolkata,24.0,84255.0,1,8,19,2021-12-05,5.0,1011060.0,learner
...,...,...,...,...,...,...,...,...,...,...,...,...,...
7,181,Karan Rao,Marketing,Hyderabad,22.0,50733.0,1,6,6,2020-04-05,92.0,608796.0,learner
67,169,Swati Chatterjee,Hr,Pune,33.0,49801.0,3,6,11,2021-08-20,93.0,597612.0,learner
33,129,Ashok Gupta,Marketing,Hyderabad,22.0,49693.0,0,4,7,2018-08-27,94.0,596316.0,learner
36,167,Meera Malhotra,Hr,Hyderabad,31.0,48822.0,4,5,4,2022-06-24,95.0,585864.0,learner
26,141,Manish Kulkarni,Hr,Chennai,27.0,45835.0,3,8,13,2022-07-21,96.0,550020.0,learner

In [201]:
df.nlargest(5,'salary')

,employee_id,name,department,city,age,salary,experience,performance_score,projects_completed,joining_date,salary_rank,annual_salary,experience_status
74,158,Tanvi Malhotra,Hr,Mumbai,32.0,88366.0,11,5,19,2021-02-26,1.0,1060392.0,experienced candidate
4,145,Isha Nair,Data Science,Hyderabad,32.0,88216.0,8,8,14,2019-11-25,2.0,1058592.0,experienced candidate
88,124,Deepak Verma,Data Science,Hyderabad,41.0,86380.0,9,7,8,2024-06-05,3.0,1036560.0,experienced candidate
84,102,Rahul Menon,Engineering,Hyderabad,38.0,84870.0,11,6,15,2021-06-07,4.0,1018440.0,experienced candidate
39,117,Pooja Malhotra,Engineering,Kolkata,24.0,84255.0,1,8,19,2021-12-05,5.0,1011060.0,learner

In [202]:
df.nsmallest(5,'performance_score')

,employee_id,name,department,city,age,salary,experience,performance_score,projects_completed,joining_date,salary_rank,annual_salary,experience_status
20,156,Aditya Kapoor,Data Science,Kolkata,26.0,69765.0,0,2,4,2020-04-12,29.0,837180.0,learner
24,170,Rahul Nair,Data Science,Kolkata,30.0,76425.0,5,2,4,2021-06-25,14.0,917100.0,learner
50,125,Sneha Bose,Marketing,Mumbai,32.0,56627.0,7,2,9,2023-07-12,77.0,679524.0,experienced candidate
76,176,Shreya Menon,Finance,Hyderabad,41.0,80597.0,9,2,18,2024-11-09,7.0,967164.0,experienced candidate
12,174,Divya Chatterjee,Finance,Kolkata,24.0,58374.0,1,3,12,2018-09-21,71.0,700488.0,learner

In [203]:
df.head()

,employee_id,name,department,city,age,salary,experience,performance_score,projects_completed,joining_date,salary_rank,annual_salary,experience_status
0,184,Swati Kapoor,Data Science,Kolkata,38.000000,70719.0,5,5,6,2021-07-02,26.0,848628.0,learner
1,154,Kavya Malhotra,Engineering,Mumbai,30.861702,77058.0,1,8,8,2024-02-05,13.0,924696.0,learner
2,171,Manish Desai,Data Science,Hyderabad,23.000000,69911.0,0,6,18,2019-04-24,28.0,838932.0,learner
3,146,Neha Das,Engineering,Pune,28.000000,69993.0,3,8,1,2022-12-13,27.0,839916.0,learner
4,145,Isha Nair,Data Science,Hyderabad,32.000000,88216.0,8,8,14,2019-11-25,2.0,1058592.0,experienced candidate

In [208]:
df['age'] = df['age'].astype(int)

In [209]:
df.head()

,employee_id,name,department,city,age,salary,experience,performance_score,projects_completed,joining_date,salary_rank,annual_salary,experience_status
0,184,Swati Kapoor,Data Science,Kolkata,38,70719.0,5,5,6,2021-07-02,26.0,848628.0,learner
1,154,Kavya Malhotra,Engineering,Mumbai,30,77058.0,1,8,8,2024-02-05,13.0,924696.0,learner
2,171,Manish Desai,Data Science,Hyderabad,23,69911.0,0,6,18,2019-04-24,28.0,838932.0,learner
3,146,Neha Das,Engineering,Pune,28,69993.0,3,8,1,2022-12-13,27.0,839916.0,learner
4,145,Isha Nair,Data Science,Hyderabad,32,88216.0,8,8,14,2019-11-25,2.0,1058592.0,experienced candidate

In [205]:
df['department'].nunique()

6

In [206]:
df['city'].unique()

array(['Kolkata', 'Mumbai', 'Hyderabad', 'Pune', 'Delhi', 'Bangalore',
       'Chennai'], dtype=object)

In [207]:
df['salary'].nunique()

89

In [210]:
df.groupby('city')

In [212]:
df.groupby('city')['salary'].max()

city
Bangalore    81112.0
Chennai      77222.0
Delhi        80358.0
Hyderabad    88216.0
Kolkata      84255.0
Mumbai       88366.0
Pune         78545.0
Name: salary, dtype: float64

In [215]:
df.groupby(['department','city'])['salary'].max()

department    city
Data Science  Bangalore    72862.0
              Delhi        76267.0
              Hyderabad    88216.0
              Kolkata      76425.0
              Mumbai       78465.0
              Pune         75498.0
Engineering   Bangalore    81112.0
              Chennai      77222.0
              Delhi        80358.0
              Hyderabad    84870.0
              Kolkata      84255.0
              Mumbai       77058.0
              Pune         78545.0
Finance       Bangalore    71062.0
              Chennai      71889.0
              Delhi        66422.0
              Hyderabad    80597.0
              Kolkata      59422.0
              Mumbai       64112.0
              Pune         62020.0
Hr            Bangalore    74505.0
              Chennai      52250.0
              Delhi        66363.0
              Hyderabad    69076.0
              Kolkata      59693.0
              Mumbai       88366.0
              Pune         68197.0
Marketing     Bangalore    63574.0
              Chennai      62969.5
              Delhi        69499.0
              Hyderabad    62393.0
              Kolkata      59186.0
              Mumbai       64944.0
              Pune         62227.0
Sales         Chennai      57858.0
              Delhi        68490.0
              Hyderabad    62969.5
              Kolkata      60015.0
              Mumbai       52862.0
Name: salary, dtype: float64

In [216]:
df.groupby('department').agg({
    'salary': ['mean','max'],
    'performance_score': 'mean',
    'employee_id': 'count'
})

                    salary          performance_score employee_id
                      mean      max              mean       count
department
Data Science  76450.800000  88216.0          5.700000          10
Engineering   74038.205882  84870.0          5.705882          17
Finance       66187.705882  80597.0          5.294118          17
Hr            59524.875000  88366.0          5.708333          24
Marketing     59382.000000  69499.0          5.894737          19
Sales         59289.055556  68490.0          6.555556           9